// <auto-generated />
namespace ImportCrud.Migrations.ImportCrud
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Alter_Cnpj_Company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alter_Cnpj_Company));
        
        string IMigrationMetadata.Id
        {
            get { return "202411181026467_Alter_Cnpj_Company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
